### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by chassain** [cowboysdude/MMM-NPR#1]
hello,

this module doesn't work for me . (disabled is false of course). 
Is there another action to do after installing github and npm install ?
Thanks

**Comment by cowboysdude** [comment]
I'd have to see your config

**Comment by chassain** [comment]
Thanks. My config is in french

{
	  		module: "MMM-NPR",
	  		position: "left",
			config: {
				type: 'world'  // world or us are the only two options.
				}
	  	},

This module requiert an api ?

**Comment by cowboysdude** [comment]
Your position is the problem    left is not a position.   'top_left'
 should work  :)

**Comment by chassain** [comment]
sorry but nothing after put "top_left"

**Comment by cowboysdude** [comment]
Can you send me your entire config minus any api keys

**Comment by chassain** [comment]
var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "fr",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
			disabled: true,
		},
		{
			module: "updatenotification",
			disabled: true,
			position: "top_bar"
		},
		{
			module: "clock",
			disabled: false,
			position: "top_bar",
			config: {
				displaySeconds: false,
				displayType: "digital",
				showWeek: false,
				analogFace: "face-003",
				}
		},
		{
			module: "calendar",
			disabled: false,
			header: "Calendrier",
			position: "center",
			config: {
				maximumEntries: 10,
				maximumNumberofDays: 60,
				colored: true,
				coloredSymbolOnly: true,
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: "https://calendar.google.com/calendar/ical/XXXXXX
					}
				]
			}
		},
		{
			module: "calendar_monthly",
			disabled: false,
			position: "right"
		},
		{
			module: "compliments",
			disabled: true,
			position: "lower_third"
		},
		{
			module: "currentweather",
			disabled: true,
			position: "middle_center",
			config: {
				location: "Hyeres",
				locationID: "3012937",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "XXXXXX",
				showHumidity: true
			}
		},
		{
			module: "weatherforecast",
			disabled: true,
			position: "middle_center",
			header: "PrÃ©visions",
			config: {
				location: "Hyeres",
				locationID: "3012937",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "XXXX",
				maxNumberOfDays: 10,
				showRainAmount: true,
				colored: true
			}
		},
		{
			module: 'MMM-WunderGround',
			disabled: false,
			position: 'bottom_center',
			config: {
				apikey: 'XXXXX', // private; don't share!
				pws: 'pws:IHYRES22', //toulon
				coloricon: true,
				hourly: '1',
				fctext: '1',
				scaletxt: "1",
				fcdaycount: "4",
				fcdaystart: "0",
				hourlyinterval: "3",
				iconset: "VCloudsWeatherIcons",
				hourlycount: "2",
				alerttime: 10000,
				alerttruncatestring: "english:",
				roundTmpDecs: 1,
				UseCardinals: 1,
				layout: "horizontal",
				sysstat: 0
				}
		},
		{
      module: "MMM-MyCommute",
      position: "right",
      header: "Trafic",
      classes: "default everyone",
      disabled: false,
      config: {
        apikey: "XXXXX",
        origin: "47 route de la Crau, 83400 Hyeres",
        startTime: "00:00",
        endTime: "23:59",
        hideDays: [],
        showSummary: true,
        colorCodeTravelTime: true,
        moderateTimeThreshold: 1.1,
        poorTimeThreshold: 1.3,
        nextTransitVehicleDepartureFormat: "[next at] h:mm a",
        travelTimeFormat: "h [h] m [min]",
        travelTimeFormatTrim: "left",
        pollFrequency: 15 * 60 * 1000, //every fiveteen minutes, in milliseconds
        destinations: [
          {
            destination: "Avenue de la Tour Royale, 83000 Toulon",
            label: "Boulot",
            mode: "driving",
            color: "#82E5AA"
          },
          {
            destination: "Gare de Toulon, 83000 Toulon",
            label: "Gare Toulon",
            mode: "driving",
            color: "#e00f35"
          },
          {
            destination: "AÃ©roport Marseille Provence",
            label: "AÃ©roport Marignane",
            mode: "driving",
            color: "#9710b2"
          },
          {
            destination: "31000 Toulouse",
            label: "Toulouse",
            mode: "driving",
            color: "#082fce"
          },
          {
            destination: "33000 Bordeaux",
            label: "Bordeaux",
            mode: "driving",
            color: "#ce6808"
          }
        ]
      }
    },
		{
			module: "MMM-GoogleMapsTraffic",
			disabled: false,
			position: "left",
			config: {
				key: "XXXXXX",
				lat: 43.26,
				lng: 5.98,
				height: "400px",
				width: "600px"
				}
		},  
		{
			module: "newsfeed",
			disabled: false,
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "BFM",
						url: "http://www.bfmtv.com/rss/info/flux-rss/flux-toutes-les-actualites/"
					},
					{
						title: "Hyeres",
						url: "http://www.hyeres.fr/getrss.html?flux=flux_actus"
					},
					{
						title: "20minutes",
						url: "http://www.20minutes.fr/rss/actu-france.xml"
					},
					{
						title: "lequipe",
						url: "http://www.lequipe.fr/rss/actu_rss.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			}
		},
		{
			module: "MMM-iFrameReload",
			disabled: true,
			position: "middle_center",	// This can be any of the regions.
			config: {
			// See 'Configuration options' for more information.
				url: ["https://alexa.amazon.fr"],	//Alexa
				width: "500px", // Optional. Default: 100%
				height: "300px", //Optional. Default: 100px
				refreshInterval: 3600

			}
		},
		{
			module: "MMM-iFrameReload",
			disabled: true,
			position: "middle_center",	// This can be any of the regions.
			config: {
			// See 'Configuration options' for more information.
				url: ["https://www.youtube.com/embed/FAE_qcnrcMw?rel=0&amp;autoplay=1"],	//londres
				width: "500px", // Optional. Default: 100%
				height: "300px", //Optional. Default: 100px
				refreshInterval: 3600

			}
		},
		{
			module: "MMM-iFrameReload",
			disabled: true,
			position: "middle_center",	// This can be any of the regions.
			config: {
			// See 'Configuration options' for more information.
				url: ["https://www.youtube.com/embed/la90mA4VLa4?rel=0&amp;autoplay=1"],	//Brooklyn
				width: "500px", // Optional. Default: 100%
				height: "300px", //Optional. Default: 100px
				refreshInterval: 3600

			}
		},
		{
			module: "MMM-iFrameReload",
			disabled: true,
			position: "middle_center",	// This can be any of the regions.
			config: {
			// See 'Configuration options' for more information.
				url: ["https://www.youtube.com/embed/ccp24-zhwdo?rel=0&amp;autoplay=1&mute=1"],	//tokyo
				width: "500px", // Optional. Default: 100%
				height: "300px", //Optional. Default: 100px
				refreshInterval: 3600

			}
		},
		{
			module: "MMM-iFrameReload",
			disabled: true,
			position: "middle_center",	// This can be any of the regions.
			config: {
			// See 'Configuration options' for more information.
				url: ["https://www.youtube.com/embed/RtU_mdL2vBM?rel=0&amp;autoplay=1&mute=1"],	//nasa
				width: "500px", // Optional. Default: 100%
				height: "300px", //Optional. Default: 100px
				refreshInterval: 3600

			}
		},
		{
			module: "MMM-iFrameReload",
			disabled: true,
			position: "middle_center",	// This can be any of the regions.
			config: {
			// See 'Configuration options' for more information.
				url: ["http://playercdn.earthtv.com/?autoplay=true&token=599d9478bbf047685d049e82&language=fr_FR&live=true&channel=live&livesd=http://cdn.liveonearth.com/stream27/cdnedge/smil:CDG.smil/playlist.m3u8"],	//paris
				width: "500px", // Optional. Default: 100%
				height: "300px", //Optional. Default: 100px
				refreshInterval: 3600

			}
		},
		{
			module: "MMM-iFrameReload",
			disabled: true,
			position: "middle_center",	// This can be any of the regions.
			config: {
			// See 'Configuration options' for more information.
				url: ["https://www.youtube.com/embed/P9qjE1dm75A?rel=0&amp;autoplay=1&mute=1"],	//venise
				width: "500px", // Optional. Default: 100%
				height: "300px", //Optional. Default: 100px
				refreshInterval: 3600

			}
		},
		{
			module: "MMM-iFrameReload",
			disabled: true,
			position: "middle_center",	// This can be any of the regions.
			config: {
			// See 'Configuration options' for more information.
				url: ["https://www.youtube.com/embed/1Ho6meL1V58?rel=0&amp;autoplay=1&mute=1"],	//prague
				width: "500px", // Optional. Default: 100%
				height: "300px", //Optional. Default: 100px
				refreshInterval: 3600

			}
		},
		{
			module: "MMM-cryptocurrency",
			position: "left",
			config: {
			currency: ['tron', 'ethereum', 'ripple'],
			conversion: 'EUR',
			significantDigits: 4,
			showUSD: false,
			headers: ['change24h', 'change1h', 'change7d'],
			displayType: 'logoWithChanges',
			showGraphs: false
			}
		},
		{
			module: "MMM-Globe",
			position: "right",
			config: {
				style: 'europeDiscNat',
				imageSize: 300,
				updateInterval: 10*60*1000
				}
		},
      		{
	  		module: "MMM-NPR",
			disabled: false,
	  		position: "top_left",
			config: {
				type: 'world'  // world or us are the only two options.
				}
	  	},
		{
   			 module: 'MMM-Lunartic',
   			 position: 'left',                   // Best in left, center, or right regions
    			config: { 
				image: "animation",                     // animation, current, DayNight or static
				distance: "km",                      // miles or km
				useHeader: false,                       // true if you want a header
				header: "",   // Any text you want
				maxWidth: "300px",
				animationSpeed: 3000,                   // updated info fades in and out
    				}
		},
     		{
           		module: 'MMM-History',
			disabled: true,
          		position: 'right',
          		config: {
        			language: "fr",
				maxWidth: "300px"  // Increase to maximum px or 100% to stretch across mirror. See Examples above.
          			}
    		},
		{
        		module: "MMM-pages",
			disabled: false,
        		config: {
                		modules:
				[[ "MMM-NPR" ],
				[ 'MMM-Lunartic' , 'MMM-WunderGround' , "MMM-Globe" ],
				[ "clock" , "calendar", "calendar_monthly" , "MMM-cryptocurrency" ],
                     		[ "clock" , "MMM-GoogleMapsTraffic" , "MMM-MyCommute" ]],
                		excludes: [ "newsfeed" , "MMM-page-indicator" ],
        			rotationTime: 25000,
				}
    		},
		{
			module: "MMM-page-indicator",
			disabled: true,
			position: "bottom_bar",
			config: {
				pages: 4,
				}
		}  
	]

};

**Comment by chassain** [comment]
thanks to you !

**Comment by cowboysdude** [comment]
It's the module......for some reason the request is being sent but it's
not getting an answer back....... I"ll have to look at it tonight or
tomorrow :)   Sorry for the trouble......it happens :)

**Comment by chassain** [comment]
it doesn't matter. Thanks to see. I m working for a another project and i m very bad about json.
i have posted some request but no response. I try to display the result of echo dot in the amazon alexa web page (like on this application phone) with my raspberry (in front of magicmirror when i tell something..and come back to the magicmirror by voice)...no easy for a beginner ! thanks again. See you.

**Comment by cowboysdude** [comment]
That's not easy for experienced people either LOL Keep at it!! Just keep
asking questions in the forum!!
